/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MarriageCertificateService } from "../marriageCertificate.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MarriageCertificateCreateInput } from "./MarriageCertificateCreateInput";
import { MarriageCertificate } from "./MarriageCertificate";
import { MarriageCertificateFindManyArgs } from "./MarriageCertificateFindManyArgs";
import { MarriageCertificateWhereUniqueInput } from "./MarriageCertificateWhereUniqueInput";
import { MarriageCertificateUpdateInput } from "./MarriageCertificateUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MarriageCertificateControllerBase {
  constructor(
    protected readonly service: MarriageCertificateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MarriageCertificate })
  @nestAccessControl.UseRoles({
    resource: "MarriageCertificate",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMarriageCertificate(
    @common.Body() data: MarriageCertificateCreateInput
  ): Promise<MarriageCertificate> {
    return await this.service.createMarriageCertificate({
      data: {
        ...data,

        person: data.person
          ? {
              connect: data.person,
            }
          : undefined,

        spouse: data.spouse
          ? {
              connect: data.spouse,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        person: {
          select: {
            id: true,
          },
        },

        spouse: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MarriageCertificate] })
  @ApiNestedQuery(MarriageCertificateFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MarriageCertificate",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async marriageCertificates(
    @common.Req() request: Request
  ): Promise<MarriageCertificate[]> {
    const args = plainToClass(MarriageCertificateFindManyArgs, request.query);
    return this.service.marriageCertificates({
      ...args,
      select: {
        createdAt: true,
        id: true,

        person: {
          select: {
            id: true,
          },
        },

        spouse: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MarriageCertificate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MarriageCertificate",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async marriageCertificate(
    @common.Param() params: MarriageCertificateWhereUniqueInput
  ): Promise<MarriageCertificate | null> {
    const result = await this.service.marriageCertificate({
      where: params,
      select: {
        createdAt: true,
        id: true,

        person: {
          select: {
            id: true,
          },
        },

        spouse: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MarriageCertificate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MarriageCertificate",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMarriageCertificate(
    @common.Param() params: MarriageCertificateWhereUniqueInput,
    @common.Body() data: MarriageCertificateUpdateInput
  ): Promise<MarriageCertificate | null> {
    try {
      return await this.service.updateMarriageCertificate({
        where: params,
        data: {
          ...data,

          person: data.person
            ? {
                connect: data.person,
              }
            : undefined,

          spouse: data.spouse
            ? {
                connect: data.spouse,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          person: {
            select: {
              id: true,
            },
          },

          spouse: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MarriageCertificate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MarriageCertificate",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMarriageCertificate(
    @common.Param() params: MarriageCertificateWhereUniqueInput
  ): Promise<MarriageCertificate | null> {
    try {
      return await this.service.deleteMarriageCertificate({
        where: params,
        select: {
          createdAt: true,
          id: true,

          person: {
            select: {
              id: true,
            },
          },

          spouse: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
