/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Person } from "./Person";
import { PersonCountArgs } from "./PersonCountArgs";
import { PersonFindManyArgs } from "./PersonFindManyArgs";
import { PersonFindUniqueArgs } from "./PersonFindUniqueArgs";
import { CreatePersonArgs } from "./CreatePersonArgs";
import { UpdatePersonArgs } from "./UpdatePersonArgs";
import { DeletePersonArgs } from "./DeletePersonArgs";
import { BankDetailFindManyArgs } from "../../bankDetail/base/BankDetailFindManyArgs";
import { BankDetail } from "../../bankDetail/base/BankDetail";
import { BirthDetailsFindManyArgs } from "../../birthDetails/base/BirthDetailsFindManyArgs";
import { BirthDetails } from "../../birthDetails/base/BirthDetails";
import { ChildFindManyArgs } from "../../child/base/ChildFindManyArgs";
import { Child } from "../../child/base/Child";
import { EducationRecordFindManyArgs } from "../../educationRecord/base/EducationRecordFindManyArgs";
import { EducationRecord } from "../../educationRecord/base/EducationRecord";
import { FamilyMemberFindManyArgs } from "../../familyMember/base/FamilyMemberFindManyArgs";
import { FamilyMember } from "../../familyMember/base/FamilyMember";
import { HealthRecordFindManyArgs } from "../../healthRecord/base/HealthRecordFindManyArgs";
import { HealthRecord } from "../../healthRecord/base/HealthRecord";
import { MarriageCertificateFindManyArgs } from "../../marriageCertificate/base/MarriageCertificateFindManyArgs";
import { MarriageCertificate } from "../../marriageCertificate/base/MarriageCertificate";
import { OtpFindManyArgs } from "../../otp/base/OtpFindManyArgs";
import { Otp } from "../../otp/base/Otp";
import { PassportDetailFindManyArgs } from "../../passportDetail/base/PassportDetailFindManyArgs";
import { PassportDetail } from "../../passportDetail/base/PassportDetail";
import { SpouseFindManyArgs } from "../../spouse/base/SpouseFindManyArgs";
import { Spouse } from "../../spouse/base/Spouse";
import { TravelDetailFindManyArgs } from "../../travelDetail/base/TravelDetailFindManyArgs";
import { TravelDetail } from "../../travelDetail/base/TravelDetail";
import { PersonService } from "../person.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Person)
export class PersonResolverBase {
  constructor(
    protected readonly service: PersonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Person",
    action: "read",
    possession: "any",
  })
  async _peopleMeta(
    @graphql.Args() args: PersonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Person])
  @nestAccessControl.UseRoles({
    resource: "Person",
    action: "read",
    possession: "any",
  })
  async people(@graphql.Args() args: PersonFindManyArgs): Promise<Person[]> {
    return this.service.people(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Person, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Person",
    action: "read",
    possession: "own",
  })
  async person(
    @graphql.Args() args: PersonFindUniqueArgs
  ): Promise<Person | null> {
    const result = await this.service.person(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Person)
  @nestAccessControl.UseRoles({
    resource: "Person",
    action: "create",
    possession: "any",
  })
  async createPerson(@graphql.Args() args: CreatePersonArgs): Promise<Person> {
    return await this.service.createPerson({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Person)
  @nestAccessControl.UseRoles({
    resource: "Person",
    action: "update",
    possession: "any",
  })
  async updatePerson(
    @graphql.Args() args: UpdatePersonArgs
  ): Promise<Person | null> {
    try {
      return await this.service.updatePerson({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Person)
  @nestAccessControl.UseRoles({
    resource: "Person",
    action: "delete",
    possession: "any",
  })
  async deletePerson(
    @graphql.Args() args: DeletePersonArgs
  ): Promise<Person | null> {
    try {
      return await this.service.deletePerson(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [BankDetail], { name: "bankDetails" })
  @nestAccessControl.UseRoles({
    resource: "BankDetail",
    action: "read",
    possession: "any",
  })
  async findBankDetails(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: BankDetailFindManyArgs
  ): Promise<BankDetail[]> {
    const results = await this.service.findBankDetails(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [BirthDetails], { name: "birthDetailsItems" })
  @nestAccessControl.UseRoles({
    resource: "BirthDetails",
    action: "read",
    possession: "any",
  })
  async findBirthDetailsItems(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: BirthDetailsFindManyArgs
  ): Promise<BirthDetails[]> {
    const results = await this.service.findBirthDetailsItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Child], { name: "children" })
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "read",
    possession: "any",
  })
  async findChildren(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: ChildFindManyArgs
  ): Promise<Child[]> {
    const results = await this.service.findChildren(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [EducationRecord], { name: "educationRecords" })
  @nestAccessControl.UseRoles({
    resource: "EducationRecord",
    action: "read",
    possession: "any",
  })
  async findEducationRecords(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: EducationRecordFindManyArgs
  ): Promise<EducationRecord[]> {
    const results = await this.service.findEducationRecords(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [FamilyMember], { name: "familyMembers" })
  @nestAccessControl.UseRoles({
    resource: "FamilyMember",
    action: "read",
    possession: "any",
  })
  async findFamilyMembers(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: FamilyMemberFindManyArgs
  ): Promise<FamilyMember[]> {
    const results = await this.service.findFamilyMembers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [HealthRecord], { name: "healthRecords" })
  @nestAccessControl.UseRoles({
    resource: "HealthRecord",
    action: "read",
    possession: "any",
  })
  async findHealthRecords(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: HealthRecordFindManyArgs
  ): Promise<HealthRecord[]> {
    const results = await this.service.findHealthRecords(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [MarriageCertificate], {
    name: "marriageCertificates",
  })
  @nestAccessControl.UseRoles({
    resource: "MarriageCertificate",
    action: "read",
    possession: "any",
  })
  async findMarriageCertificates(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: MarriageCertificateFindManyArgs
  ): Promise<MarriageCertificate[]> {
    const results = await this.service.findMarriageCertificates(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Otp], { name: "otps" })
  @nestAccessControl.UseRoles({
    resource: "Otp",
    action: "read",
    possession: "any",
  })
  async findOtps(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: OtpFindManyArgs
  ): Promise<Otp[]> {
    const results = await this.service.findOtps(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [PassportDetail], { name: "passportDetails" })
  @nestAccessControl.UseRoles({
    resource: "PassportDetail",
    action: "read",
    possession: "any",
  })
  async findPassportDetails(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: PassportDetailFindManyArgs
  ): Promise<PassportDetail[]> {
    const results = await this.service.findPassportDetails(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Spouse], { name: "spouses" })
  @nestAccessControl.UseRoles({
    resource: "Spouse",
    action: "read",
    possession: "any",
  })
  async findSpouses(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: SpouseFindManyArgs
  ): Promise<Spouse[]> {
    const results = await this.service.findSpouses(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [TravelDetail], { name: "travelDetails" })
  @nestAccessControl.UseRoles({
    resource: "TravelDetail",
    action: "read",
    possession: "any",
  })
  async findTravelDetails(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: TravelDetailFindManyArgs
  ): Promise<TravelDetail[]> {
    const results = await this.service.findTravelDetails(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
