/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Ssn as PrismaSsn } from "@prisma/client";

export class SsnServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SsnCountArgs, "select">): Promise<number> {
    return this.prisma.ssn.count(args);
  }

  async ssns(args: Prisma.SsnFindManyArgs): Promise<PrismaSsn[]> {
    return this.prisma.ssn.findMany(args);
  }
  async ssn(args: Prisma.SsnFindUniqueArgs): Promise<PrismaSsn | null> {
    return this.prisma.ssn.findUnique(args);
  }
  async createSsn(args: Prisma.SsnCreateArgs): Promise<PrismaSsn> {
    return this.prisma.ssn.create(args);
  }
  async updateSsn(args: Prisma.SsnUpdateArgs): Promise<PrismaSsn> {
    return this.prisma.ssn.update(args);
  }
  async deleteSsn(args: Prisma.SsnDeleteArgs): Promise<PrismaSsn> {
    return this.prisma.ssn.delete(args);
  }
}
