/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SsnService } from "../ssn.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SsnCreateInput } from "./SsnCreateInput";
import { Ssn } from "./Ssn";
import { SsnFindManyArgs } from "./SsnFindManyArgs";
import { SsnWhereUniqueInput } from "./SsnWhereUniqueInput";
import { SsnUpdateInput } from "./SsnUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SsnControllerBase {
  constructor(
    protected readonly service: SsnService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ssn })
  @nestAccessControl.UseRoles({
    resource: "Ssn",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSsn(@common.Body() data: SsnCreateInput): Promise<Ssn> {
    return await this.service.createSsn({
      data: data,
      select: {
        createdAt: true,
        expirationDate: true,
        id: true,
        issuedDate: true,
        numberField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Ssn] })
  @ApiNestedQuery(SsnFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Ssn",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ssns(@common.Req() request: Request): Promise<Ssn[]> {
    const args = plainToClass(SsnFindManyArgs, request.query);
    return this.service.ssns({
      ...args,
      select: {
        createdAt: true,
        expirationDate: true,
        id: true,
        issuedDate: true,
        numberField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ssn })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ssn",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ssn(@common.Param() params: SsnWhereUniqueInput): Promise<Ssn | null> {
    const result = await this.service.ssn({
      where: params,
      select: {
        createdAt: true,
        expirationDate: true,
        id: true,
        issuedDate: true,
        numberField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ssn })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ssn",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSsn(
    @common.Param() params: SsnWhereUniqueInput,
    @common.Body() data: SsnUpdateInput
  ): Promise<Ssn | null> {
    try {
      return await this.service.updateSsn({
        where: params,
        data: data,
        select: {
          createdAt: true,
          expirationDate: true,
          id: true,
          issuedDate: true,
          numberField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ssn })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ssn",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSsn(
    @common.Param() params: SsnWhereUniqueInput
  ): Promise<Ssn | null> {
    try {
      return await this.service.deleteSsn({
        where: params,
        select: {
          createdAt: true,
          expirationDate: true,
          id: true,
          issuedDate: true,
          numberField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
