/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Guest } from "./Guest";
import { GuestCountArgs } from "./GuestCountArgs";
import { GuestFindManyArgs } from "./GuestFindManyArgs";
import { GuestFindUniqueArgs } from "./GuestFindUniqueArgs";
import { DeleteGuestArgs } from "./DeleteGuestArgs";
import { GuestService } from "../guest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Guest)
export class GuestResolverBase {
  constructor(
    protected readonly service: GuestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "read",
    possession: "any",
  })
  async _guestsMeta(
    @graphql.Args() args: GuestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Guest])
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "read",
    possession: "any",
  })
  async guests(@graphql.Args() args: GuestFindManyArgs): Promise<Guest[]> {
    return this.service.guests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Guest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "read",
    possession: "own",
  })
  async guest(
    @graphql.Args() args: GuestFindUniqueArgs
  ): Promise<Guest | null> {
    const result = await this.service.guest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Guest)
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "delete",
    possession: "any",
  })
  async deleteGuest(
    @graphql.Args() args: DeleteGuestArgs
  ): Promise<Guest | null> {
    try {
      return await this.service.deleteGuest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
